`default_nettype none
`timescale 1ns / 1ps
// =============================================================================
// tb_fir_decimate.v — FIR decimation filter unit test
//
// Loads known coefficients and input data from hex files.
// Compares output against reference (generated by Python gen_test_vectors.py).
// =============================================================================
module tb_fir_decimate;

    // =========================================================================
    // Parameters
    // =========================================================================
    parameter CLK_PERIOD = 10;
    parameter DATA_W     = 18;
    parameter COEFF_W    = 18;
    parameter ACC_W      = 48;
    parameter MAX_TAPS   = 128;
    parameter NUM_TAPS   = 16;
    parameter DECIM_R    = 4;
    parameter NUM_INPUT  = 256;
    parameter NUM_OUTPUT = NUM_INPUT / DECIM_R;
    parameter TAP_ADDR_W = $clog2(MAX_TAPS);

    // =========================================================================
    // Signals
    // =========================================================================
    reg                     clk;
    reg                     rst;

    reg  [TAP_ADDR_W-1:0]  cfg_tap_count;
    reg  [3:0]              cfg_decim_ratio;

    reg  [TAP_ADDR_W-1:0]  coeff_addr;
    reg  [31:0]             coeff_wdata;
    reg                     coeff_wr;

    reg  signed [DATA_W-1:0] i_in, q_in;
    reg                      in_valid;
    wire                     in_ready;

    wire signed [DATA_W-1:0] i_out, q_out;
    wire                     out_valid;
    reg                      out_ready;

    // =========================================================================
    // DUT
    // =========================================================================
    fir_decimate #(
        .MAX_TAPS (MAX_TAPS),
        .DATA_W   (DATA_W),
        .COEFF_W  (COEFF_W),
        .ACC_W    (ACC_W)
    ) u_dut (
        .clk            (clk),
        .rst            (rst),
        .cfg_tap_count  (cfg_tap_count),
        .cfg_decim_ratio(cfg_decim_ratio),
        .coeff_addr     (coeff_addr),
        .coeff_wdata    (coeff_wdata),
        .coeff_wr       (coeff_wr),
        .i_in           (i_in),
        .q_in           (q_in),
        .in_valid       (in_valid),
        .in_ready       (in_ready),
        .i_out          (i_out),
        .q_out          (q_out),
        .out_valid      (out_valid),
        .out_ready      (out_ready)
    );

    // =========================================================================
    // Clock generation
    // =========================================================================
    initial clk = 0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // =========================================================================
    // Test data
    // =========================================================================
    reg signed [DATA_W-1:0] test_coeffs [0:MAX_TAPS-1];
    reg signed [DATA_W-1:0] test_input_i [0:NUM_INPUT-1];
    reg signed [DATA_W-1:0] test_input_q [0:NUM_INPUT-1];
    reg signed [DATA_W-1:0] ref_output_i [0:NUM_OUTPUT-1];
    reg signed [DATA_W-1:0] ref_output_q [0:NUM_OUTPUT-1];

    initial begin
        $readmemh("reference/fir_coeffs.hex", test_coeffs);
        $readmemh("reference/fir_input_i.hex", test_input_i);
        $readmemh("reference/fir_input_q.hex", test_input_q);
        $readmemh("reference/fir_output_i.hex", ref_output_i);
        $readmemh("reference/fir_output_q.hex", ref_output_q);
    end

    // =========================================================================
    // Test sequence
    // =========================================================================
    integer i;
    integer out_idx;
    integer errors;
    integer max_err_i, max_err_q;
    integer err_i, err_q;

    // Output capture
    reg signed [DATA_W-1:0] cap_i [0:NUM_OUTPUT-1];
    reg signed [DATA_W-1:0] cap_q [0:NUM_OUTPUT-1];

    initial begin
        $dumpfile("tb_fir_decimate.vcd");
        $dumpvars(0, tb_fir_decimate);

        // Initialize
        rst             = 1;
        cfg_tap_count   = NUM_TAPS;
        cfg_decim_ratio = DECIM_R;
        coeff_addr      = 0;
        coeff_wdata     = 0;
        coeff_wr        = 0;
        i_in            = 0;
        q_in            = 0;
        in_valid        = 0;
        out_ready       = 1;
        errors          = 0;
        max_err_i       = 0;
        max_err_q       = 0;
        out_idx         = 0;

        // Reset
        #(CLK_PERIOD * 10);
        rst = 0;
        #(CLK_PERIOD * 5);

        // ----- Load coefficients -----
        $display("Loading %0d FIR coefficients...", NUM_TAPS);
        for (i = 0; i < NUM_TAPS; i = i + 1) begin
            @(posedge clk);
            coeff_addr  <= i;
            coeff_wdata <= {{(32-COEFF_W){test_coeffs[i][COEFF_W-1]}}, test_coeffs[i]};
            coeff_wr    <= 1;
            @(posedge clk);
            coeff_wr    <= 0;
        end
        #(CLK_PERIOD * 5);

        // ----- Feed input data -----
        $display("Feeding %0d input samples (decim=%0d, expect %0d outputs)...",
                 NUM_INPUT, DECIM_R, NUM_OUTPUT);

        for (i = 0; i < NUM_INPUT; i = i + 1) begin
            @(posedge clk);
            i_in     <= test_input_i[i];
            q_in     <= test_input_q[i];
            in_valid <= 1;

            // Wait for ready
            while (!in_ready) @(posedge clk);
            @(posedge clk);
            in_valid <= 0;

            // Wait for filter computation to complete
            #(CLK_PERIOD * (NUM_TAPS + 10));
        end

        in_valid <= 0;

        // Wait for all outputs to emerge
        #(CLK_PERIOD * 200);

        // ----- Compare outputs -----
        $display("Captured %0d outputs, comparing...", out_idx);
        for (i = 0; i < out_idx && i < NUM_OUTPUT; i = i + 1) begin
            err_i = (cap_i[i] > ref_output_i[i]) ?
                    (cap_i[i] - ref_output_i[i]) : (ref_output_i[i] - cap_i[i]);
            err_q = (cap_q[i] > ref_output_q[i]) ?
                    (cap_q[i] - ref_output_q[i]) : (ref_output_q[i] - cap_q[i]);

            if (err_i > max_err_i) max_err_i = err_i;
            if (err_q > max_err_q) max_err_q = err_q;

            // Allow tolerance of 2 LSBs for rounding
            if (err_i > 2 || err_q > 2) begin
                $display("  MISMATCH at output[%0d]: got I=%0d Q=%0d, expected I=%0d Q=%0d",
                         i, cap_i[i], cap_q[i], ref_output_i[i], ref_output_q[i]);
                errors = errors + 1;
            end
        end

        $display("Max error: I=%0d Q=%0d LSBs", max_err_i, max_err_q);
        $display("=== FIR Decimation Test: %0d errors ===", errors);
        if (errors == 0)
            $display("PASS");
        else
            $display("FAIL");

        $finish;
    end

    // =========================================================================
    // Output capture
    // =========================================================================
    always @(posedge clk) begin
        if (out_valid && out_ready && out_idx < NUM_OUTPUT) begin
            cap_i[out_idx] <= i_out;
            cap_q[out_idx] <= q_out;
            out_idx = out_idx + 1;
            $display("  Output[%0d]: I=%0d Q=%0d", out_idx - 1, i_out, q_out);
        end
    end

endmodule
`default_nettype wire
